server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  h2:
    console:
      enabled: ${convertfactorms.h2.console.enabled:true}
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: "jdbc:h2:mem:conversionDB:DB_CLOSE_DELAY=-1"
    username: ${convertfactorms.datasource.username}
    password: ${convertfactorms.datasource.password}
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        ddl-auto: create-drop  
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.99.100:9411/
  rabbitmq:
    host: 192.168.99.100
    port: 5672
  cloud:
    bus:
      enabled: true
      destination: configXchangebus                
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    metadata-map:
      zone: A
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: ${convertfactorms.eureka.url:http://192.168.99.100:8761/eureka}
 
      
        
        
