server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  cloud:
    config:
      server:
        git:
          #uri: C:\work\ksr\kolkata2020labsconfig
          uri: https://github.com/ragabmss/microservice.git
          username: ragabms@gmail.com
          password: Swakur@21
          skipSslValidation: true  
    bus:
      enabled: true
      destination: configXchangebus                   
  